---
  # gsettings set org.gnome.shell favorite-apps \
  # newuser: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'gnome-screenshot.desktop', 'org.gnome.gedit.desktop', 'evolution.desktop', 'libreoffice-writer.desktop', 'org.gnome.Software.desktop']"
  # mine: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'libreoffice-writer.desktop', 'org.gnome.Software.desktop', 'terminator.desktop', 'code.desktop', 'gitkraken.desktop', 'virtualbox.desktop', 'putty.desktop', 'org.gnome.Screenshot.desktop', 'spotify.desktop']"

# FYI: Only works in bionic - See playbook.yml

- name: Set favbar (native)
  gsetting:
    user: "{{ setup_user }}"
    key: org.gnome.shell.favorite-apps
    value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'libreoffice-writer.desktop', 'org.gnome.Software.desktop', 'terminator.desktop', 'code.desktop', 'gitkraken.desktop', 'virtualbox.desktop', 'putty.desktop', 'org.gnome.Screenshot.desktop', 'spotify.desktop']"
  when: is_vm == 0

- name: Set favbar (VM)
  gsetting:
    user: "{{ setup_user }}"
    key: org.gnome.shell.favorite-apps
    value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'libreoffice-writer.desktop', 'org.gnome.Software.desktop', 'terminator.desktop', 'code.desktop', 'gitkraken.desktop', 'putty.desktop', 'org.gnome.Screenshot.desktop']"
  when: is_vm == 1
